atomisp-ov883x: (port-to-v4.1) replace v4l2_subdev_fh by v4l2_subdev_pad_config
In accordance with commit f7234138f14c ("[media] v4l2-subdev: replace
v4l2_subdev_fh by v4l2_subdev_pad_config") added on v4.1-rc1.

Fixes the errors like the following:

    atomisp-ov883x/atomisp-ov883x.c: In function ‘__ov8830_get_pad_format’:
    atomisp-ov883x/atomisp-ov883x.c:1531:37: error: passing argument 1 of ‘v4l2_subdev_get_try_format’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     1531 |   return v4l2_subdev_get_try_format(fh, pad);
          |                                     ^~
          |                                     |
          |                                     struct v4l2_subdev_fh *
    In file included from ./include/media/v4l2-device.h:13,
                     from atomisp-ov883x/atomisp-ov883x.c:42:
    ./include/media/v4l2-subdev.h:977:49: note: expected ‘struct v4l2_subdev *’ but argument is of type ‘struct v4l2_subdev_fh *’
      977 | *v4l2_subdev_get_try_format(struct v4l2_subdev *sd,
          |                             ~~~~~~~~~~~~~~~~~~~~^~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>