atomisp-ar0330: (port-to-v4.5) use media_entity_pads_init() instead of media_entity_init()
Fixes the following compile error:

    atomisp-ar0330/atomisp-ar0330.c: In function ‘ar0330_probe’:
    atomisp-ar0330/atomisp-ar0330.c:1053:8: error: implicit declaration of function ‘media_entity_init’; did you mean ‘media_entity_id’? [-Werror=implicit-function-declaration]
    1053 |  ret = media_entity_init(&sd->entity, 1, &ar0330->pad, 0);
         |        ^~~~~~~~~~~~~~~~~
         |        media_entity_id

in accordance with commit
- 1809510715c4 ("[media] media: get rid of unused "extra_links" param
  on media_entity_init()") added on v4.5-rc1
[argument number change] and commit
- ab22e77cd3d3 ("[media] media framework: rename pads init function to
  media_entity_pads_init()") added on v4.5-rc1
[function name change].

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>