atomisp-ov883x: (port-to-v4.1) drop enum_frameintervals() and add enum_frame_interval()
In accordance with commit 17bef885249d ("[media] v4l2-subdev: add support
for the new enum_frame_interval 'which' field") added on v4.1-rc1.

Fixes the following compile error:

    atomisp-ov883x/atomisp-ov883x.c:1718:21: note: (near initialization for ‘ov8830_video_ops.g_pixelaspect’)
    atomisp-ov883x/atomisp-ov883x.c:1719:3: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘enum_frameintervals’; did you mean ‘g_frame_interval’?
     1719 |  .enum_frameintervals = ov8830_enum_frameintervals,
          |   ^~~~~~~~~~~~~~~~~~~
          |   g_frame_interval
    atomisp-ov883x/atomisp-ov883x.c:1719:25: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_frame_interval *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_frmivalenum *)’ [-Werror=incompatible-pointer-types]
     1719 |  .enum_frameintervals = ov8830_enum_frameintervals,
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>