micam: ov5693: (port-to-v3.19) just avoid using v4l2_mbus_pixelcode for now
The commit aa1b4da6af67 ("[media] v4l: Forbid usage of V4L2_MBUS_FMT
definitions inside the kernel") added on v3.19-rc1 forbids v4l2_mbus_pixelcode
usage. Although the proper solution for this is to remove enum_mbus_fmt
op, Intel instead did like this patch.

Here is the diff between Xiaomi Mi Pad 2 kernel (based on v3.14) [1] and
the intel-aero kernel (bassed on v4.4) [2]:

        --- a/v3.14-xiaomi_latte/drivers/external_drivers/camera/drivers/media/i2c/ov8858.c
        +++ b/ov8858.c
         static int ov8858_enum_mbus_fmt(struct v4l2_subdev *sd, unsigned int index,
        -                               enum v4l2_mbus_pixelcode *code)
        +                               u32 *code)
         {
        -       *code = V4L2_MBUS_FMT_SBGGR10_1X10;
        +       *code = MEDIA_BUS_FMT_SBGGR10_1X10;
                return 0;
         }

The commit message of atomisp in the intel-aero kernel [3] says:

        > 16) NEED TO REVIST THE CODE LATER: to clean the deprecated function pointers in struct v4l2_subdev_video_ops
        >     with better approach. The function pointers are enum_framesizes, enum_frameintervals, enum_mbus_fmt
        >     g_mbus_fmt, try_mbus_fmt, and s_mbus_fmt.

It might be still used by atomisp driver? I don't know yet. Need to
revisit later.

[1] https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/78fbd35b6c73ee51129d690c4306f320e40a1401
[2] https://github.com/intel-aero/linux-kernel/tree/a1b673258feb915268377275130c5c5df0eafc82
[3] https://github.com/intel-aero/linux-kernel/commit/e979a254d48d1a65919c307fea4f08a0e638e4a5

Anyway, this commit avoids the following build errors:

        micam/atomisp-ov5693.c: At top level:
        micam/atomisp-ov5693.c:1986:38: warning: ‘enum v4l2_mbus_pixelcode’ declared inside parameter list will not be visible outside of this definition or declaration
         1986 |                                 enum v4l2_mbus_pixelcode *code)
              |                                      ^~~~~~~~~~~~~~~~~~~
        micam/atomisp-ov5693.c: In function ‘ov5693_enum_mbus_fmt’:
        micam/atomisp-ov5693.c:1988:15: error: invalid use of undefined type ‘enum v4l2_mbus_pixelcode’
         1988 |         *code = MEDIA_BUS_FMT_SBGGR10_1X10;
              |               ^

        micam/atomisp-ov5693.c: At top level:
        micam/atomisp-ov5693.c:2203:26: warning: initialization of ‘int (*)(struct v4l2_subdev *, unsigned int,  u32 *)’ {aka ‘int (*)(struct v4l2_subdev *, unsigned int,  unsigned int *)’} from incompatible pointer type ‘int (*)(struct v4l2_subdev *, unsigned int,  enum v4l2_mbus_pixelcode *)’ [-Wincompatible-pointer-types]
         2203 |         .enum_mbus_fmt = ov5693_enum_mbus_fmt,
              |                          ^~~~~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>