(port-to-v4.5) ar0330: use media_entity_pads_init instead of deprecated media_entity_init
in accordance with the following commits
- 1809510715c4 ("[media] media: get rid of unused "extra_links" param
  on media_entity_init()") added on v4.5-rc1
[argument number change] and commit
- ab22e77cd3d3 ("[media] media framework: rename pads init function to
  media_entity_pads_init()") added on v4.5-rc1
[function name change].

Fixes errors like the following:

        atomisp-ar0330/micam/atomisp-t4ka3.c: In function ‘t4ka3_probe’:
        atomisp-ar0330/micam/atomisp-t4ka3.c:2076:15: error: implicit declaration of function ‘media_entity_init’; did you mean ‘media_entity_put’? [-Werror=implicit-function-declaration]
         2076 |         ret = media_entity_init(&dev->sd.entity, 1, &dev->pad, 0);
              |               ^~~~~~~~~~~~~~~~~
              |               media_entity_put

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>