(port-to-v5.0) micam/ov5693: convert timestamps to ktime_t
Commit 437e78d3fd6d ("timekeeping: remove timespec_add/timespec_del")
on v5.0 removed timespec_add()/timespec_sub(). So, convert it.

Ref:
- 456e7b1804f7 ("media: staging: atomisp: convert timestamps to ktime_t")
- ec8354b98b60 ("staging: imx: use ktime_t for timestamps")

Fixes:

        micam/atomisp-ov5693.c: In function ‘ov5693_q_focus_status’:
        micam/atomisp-ov5693.c:1256:20: error: implicit declaration of function ‘timespec_sub’; did you mean ‘timespec64_sub’? [-Werror=implicit-function-declaration]
         1256 |         temptime = timespec_sub(temptime, (dev->timestamp_t_focus_abs));
              |                    ^~~~~~~~~~~~
              |                    timespec64_sub

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>