atomisp-ar0330: (port-to-v4.5) rename entity.type to entity.function
Fixes the following compile error:

    atomisp-ar0330/atomisp-ar0330.c: In function ‘ar0330_probe’:
    atomisp-ar0330/atomisp-ar0330.c:1052:12: error: ‘struct media_entity’ has no member named ‘type’
    1052 |  sd->entity.type = MEDIA_ENT_T_V4L2_SUBDEV_SENSOR;
         |            ^

in accordance with commit 0e576b76f547 ("[media] media-entity.h: rename
entity.type to entity.function") added on v4.5-rc1.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>