(port-to-v4.5) t4ka3: rename entity.type to entity.function
Fixes build errors like the following:

        micam/atomisp-ov5693.c: In function ‘ov5693_probe’:
        micam/atomisp-ov5693.c:2235:23: error: ‘struct media_entity’ has no member named ‘type’
         2235 |         dev->sd.entity.type = MEDIA_ENT_T_V4L2_SUBDEV_SENSOR;
              |                       ^

in accordance with commit 0e576b76f547 ("[media] media-entity.h: rename
entity.type to entity.function") added on v4.5-rc1.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>