atomisp-ov883x: (port-to-v3.19) use MEDIA_BUS_FMT_SBGGR10_1X10 instead
In accordance with commit f5fe58fd76a0 ("[media] i2c: Make use of
media_bus_format enum") added on v3.19-rc1.

Fixes compile errors like the following:

    atomisp-ov883x/atomisp-ov883x.c: In function ‘__ov8830_try_mbus_fmt’:
    atomisp-ov883x/atomisp-ov883x.c:1200:14: error: ‘V4L2_MBUS_FMT_SBGGR10_1X10’ undeclared (first use in this function); did you mean ‘MEDIA_BUS_FMT_SBGGR10_1X10’?
     1200 |  fmt->code = V4L2_MBUS_FMT_SBGGR10_1X10;
          |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
          |              MEDIA_BUS_FMT_SBGGR10_1X10

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>