atomisp-ov883x: (port-to-v5.0) convert to use timespec64
In accordance with commit 437e78d3fd6d ("timekeeping: remove timespec_add
/timespec_del") added on v5.0-rc1.

Fixes compile errors like the following:

    atomisp-ov883x/atomisp-ov883x.c: In function ‘ov8830_g_ctrl’:
    atomisp-ov883x/atomisp-ov883x.c:1491:17: error: implicit declaration of function ‘timespec_add’; did you mean ‘timespec64_add’? [-Werror=implicit-function-declaration]
     1491 |   finish_time = timespec_add(drv201->focus_time, move_time);
          |                 ^~~~~~~~~~~~
          |                 timespec64_add
    atomisp-ov883x/atomisp-ov883x.c:1491:17: error: incompatible types when assigning to type ‘struct timespec’ from type ‘int’
    atomisp-ov883x/atomisp-ov883x.c:1492:16: error: implicit declaration of function ‘timespec_sub’; did you mean ‘timespec64_sub’? [-Werror=implicit-function-declaration]
     1492 |   delta_time = timespec_sub(current_time, finish_time);
          |                ^~~~~~~~~~~~
          |                timespec64_sub

Also replaces getnstimeofday() with ktime_get_real_ts64() due to
getnstimeofday() not compatible with timespec64.

    atomisp-ov883x/atomisp-ov883x.c: In function ‘drv201_t_focus_abs’:
    atomisp-ov883x/atomisp-ov883x.c:475:17: error: passing argument 1 of ‘getnstimeofday’ from incompatible pointer type [-Werror=incompatible-pointer-types]
      475 |  getnstimeofday(&dev->focus_time);
          |                 ^~~~~~~~~~~~~~~~
          |                 |
          |                 struct timespec64 *
    In file included from ./include/linux/ktime.h:276,
                     from ./include/linux/timer.h:6,
                     from ./include/linux/workqueue.h:9,
                     from ./include/linux/srcu.h:21,
                     from ./include/linux/notifier.h:16,
                     from ./arch/x86/include/asm/uprobes.h:13,
                     from ./include/linux/uprobes.h:49,
                     from ./include/linux/mm_types.h:14,
                     from ./include/linux/mmzone.h:21,
                     from ./include/linux/gfp.h:6,
                     from ./include/linux/umh.h:4,
                     from ./include/linux/kmod.h:9,
                     from ./include/linux/module.h:13,
                     from atomisp-ov883x/atomisp-ov883x.c:22:
    ./include/linux/timekeeping32.h:14:52: note: expected ‘struct timespec *’ but argument is of type ‘struct timespec64 *’

Reference commit for the change to ktime_get_real_ts64(): d413fcb436f7
("packet: clarify timestamp overflow") added on v5.6-rc1.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>