atomisp-ov883x: (port-to-v4.5) rename to MEDIA_ENT_F_CAM_SENSOR
Fixes the following compile error:

    atomisp-ov883x/atomisp-ov883x.c:1911:24: error: ‘MEDIA_ENT_T_V4L2_SUBDEV_SENSOR’ undeclared (first use in this function); did you mean ‘MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN’?
     1911 |  dev->sd.entity.type = MEDIA_ENT_T_V4L2_SUBDEV_SENSOR;
          |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |                        MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN

in accordance with commit 4ca72efaeffd ("[media] uapi/media.h: Rename
entities types to functions") added on v4.5-rc1.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>