atomisp-ov883x: (port-to-v4.1) drop ov8830_enum_framesizes() in favor of ov8830_enum_frame_size()
In accordance with commit 17bef885249d ("[media] v4l2-subdev: add support
for the new enum_frame_interval 'which' field") added on v4.1-rc1.

There is already ov8830_enum_frame_size() defined, so just removing
ov8830_enum_framesizes() code.

Fixes the following compile error:

    atomisp-ov883x/atomisp-ov883x.c:1707:3: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘enum_framesizes’
     1707 |  .enum_framesizes = ov8830_enum_framesizes,
          |   ^~~~~~~~~~~~~~~
    atomisp-ov883x/atomisp-ov883x.c:1718:21: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_fract *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_frmsizeenum *)’ [-Werror=incompatible-pointer-types]
     1718 |  .enum_framesizes = ov8830_enum_framesizes,
          |                     ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>