micam: t4ka3: (port-to-v3.19) use MEDIA_BUS_FMT_SGRBG10_1X10 instead
In accordance with commit f5fe58fd76a0 ("[media] i2c: Make use of
media_bus_format enum") added on v3.19-rc1.

Fixes compile errors like the following:

        micam/t4ka3.h:948:25: error: ‘V4L2_MBUS_FMT_SGRBG10_1X10’ undeclared here (not in a function); did you mean ‘MEDIA_BUS_FMT_SGRBG10_1X10’?
          948 |                 .code = V4L2_MBUS_FMT_SGRBG10_1X10,
              |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
              |                         MEDIA_BUS_FMT_SGRBG10_1X10

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>