atomisp-ar0330: (port-to-v4.5) Rename entities types to functions
Fixes the following compile error:

    atomisp-ar0330/atomisp-ar0330.c: In function ‘ar0330_probe’:
    atomisp-ar0330/atomisp-ar0330.c:1052:24: error: ‘MEDIA_ENT_T_V4L2_SUBDEV_SENSOR’ undeclared (first use in this function); did you mean ‘MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN’?
    1052 |  sd->entity.function = MEDIA_ENT_T_V4L2_SUBDEV_SENSOR;
         |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         |                        MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN
    atomisp-ar0330/atomisp-ar0330.c:1052:24: note: each undeclared identifier is reported only once for each function it appears in

in accordance with commit 4ca72efaeffd ("[media] uapi/media.h: Rename
entities types to functions") added on v4.5-rc1.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>