micam: ov5693: (port-to-v5.8) adapt to upstream gmin_get_var_int()
In accordance with commit 85df8457b31c ("media: atomisp: better display
DMI and EFI found entries").

Fixes the following build errors:

        micam/atomisp-ov5693.c: In function ‘ov5693_probe’:
        micam/atomisp-ov5693.c:2261:57: warning: passing argument 3 of ‘gmin_get_var_int’ makes pointer from integer without a cast [-Wint-conversion]
         2261 |         i2c = gmin_get_var_int(&client->dev, "I2CAddr", -1);
              |                                                         ^~
              |                                                         |
              |                                                         int
        In file included from micam/atomisp-ov5693.c:40:
        micam/include/atomisp_gmin_platform.h:28:34: note: expected ‘const char *’ but argument is of type ‘int’
           28 |                      const char *var, int def);
              |                      ~~~~~~~~~~~~^~~
        micam/atomisp-ov5693.c:2261:15: error: too few arguments to function ‘gmin_get_var_int’
         2261 |         i2c = gmin_get_var_int(&client->dev, "I2CAddr", -1);
              |               ^~~~~~~~~~~~~~~~
        In file included from micam/atomisp-ov5693.c:40:
        micam/include/atomisp_gmin_platform.h:27:5: note: declared here
           27 | int gmin_get_var_int(struct device *dev, bool is_gmin,
              |     ^~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>