atomisp-ov883x: (port-to-v4.5) rename entity.type to entity.function
Fixes the following compile error:

    atomisp-ov883x/atomisp-ov883x.c: In function ‘ov8830_probe’:
    atomisp-ov883x/atomisp-ov883x.c:1911:16: error: ‘struct media_entity’ has no member named ‘type’
     1911 |  dev->sd.entity.type = MEDIA_ENT_T_V4L2_SUBDEV_SENSOR;
          |                ^

in accordance with commit 0e576b76f547 ("[media] media-entity.h: rename
entity.type to entity.function") added on v4.5-rc1.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>