atomisp-ov883x: (port-to-v4.2) drop try_mbus_fmt and s_mbus_fmt video op in favor of set_fmt pad op
In accordancce with commit 717fd5b4907a ("[media] v4l2: replace try_mbus_fmt
by set_fmt") added on v4.2-rc1.

This commit just drops try_mbus_fmt and s_mbus_fmt because set_fmt is
already defined.

Fixes the following compile errors:

    atomisp-ov883x/atomisp-ov883x.c:1700:3: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘try_mbus_fmt’
     1700 |  .try_mbus_fmt = ov8830_try_mbus_fmt,
          |   ^~~~~~~~~~~~
    atomisp-ov883x/atomisp-ov883x.c:1700:18: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_fract *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_mbus_framefmt *)’ [-Werror=incompatible-pointer-types]
     1700 |  .try_mbus_fmt = ov8830_try_mbus_fmt,
          |                  ^~~~~~~~~~~~~~~~~~~
    atomisp-ov883x/atomisp-ov883x.c:1685:3: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘s_mbus_fmt’; did you mean ‘s_mbus_config’?
     1685 |  .s_mbus_fmt = ov8830_s_mbus_fmt,
          |   ^~~~~~~~~~
          |   s_mbus_config
    atomisp-ov883x/atomisp-ov883x.c:1685:16: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_dv_timings *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_mbus_framefmt *)’ [-Werror=incompatible-pointer-types]
     1685 |  .s_mbus_fmt = ov8830_s_mbus_fmt,
          |                ^~~~~~~~~~~~~~~~~

TODO: I feel that definition os set_fmt if too small compared to the
removed ones. Do I need to port code?

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>