atomisp-ov883x: (port-to-v4.5) use media_entity_pads_init instead of deprecated media_entity_init
Fixes the following compile error:

    atomisp-ov883x/atomisp-ov883x.c: In function ‘ov8830_probe’:
    atomisp-ov883x/atomisp-ov883x.c:1936:8: error: implicit declaration of function ‘media_entity_init’; did you mean ‘media_entity_id’? [-Werror=implicit-function-declaration]
     1936 |  ret = media_entity_init(&dev->sd.entity, 1, &dev->pad, 0);
          |        ^~~~~~~~~~~~~~~~~
          |        media_entity_id

in accordance with the following commits
- 1809510715c4 ("[media] media: get rid of unused "extra_links" param
  on media_entity_init()") added on v4.5-rc1
[argument number change] and commit
- ab22e77cd3d3 ("[media] media framework: rename pads init function to
  media_entity_pads_init()") added on v4.5-rc1
[function name change].

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>