micam: ov5693: (port-to-v3.19) use MEDIA_BUS_FMT_SBGGR10_1X10 instead
In accordance with commit f5fe58fd76a0 ("[media] i2c: Make use of
media_bus_format enum") added on v3.19-rc1.

Fixes compile errors like the following:

        micam/atomisp-ov5693.c: In function ‘ov5693_try_mbus_fmt’:
        micam/atomisp-ov5693.c:1769:21: error: ‘V4L2_MBUS_FMT_SBGGR10_1X10’ undeclared (first use in this function); did you mean ‘MEDIA_BUS_FMT_SBGGR10_1X10’?
         1769 |         fmt->code = V4L2_MBUS_FMT_SBGGR10_1X10;
              |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
              |                     MEDIA_BUS_FMT_SBGGR10_1X10

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>