atomisp-ov883x: (port-to-v4.2) drop g_mbus_fmt video op in favor of get_fmt pad op
In accordance with commit da298c6d98d5 ("[media] v4l2: replace video op
g_mbus_fmt by pad op get_fmt") added on v4.2-rc1.

This commit just drops g_mbus_fmt because get_fmt is already defined.

Fixes the following errors:

    atomisp-ov883x/atomisp-ov883x.c:1595:3: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘g_mbus_fmt’; did you mean ‘g_mbus_config’?
     1595 |  .g_mbus_fmt = ov8830_g_mbus_fmt,
          |   ^~~~~~~~~~
          |   g_mbus_config
    atomisp-ov883x/atomisp-ov883x.c:1595:16: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_fract *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_mbus_framefmt *)’ [-Werror=incompatible-pointer-types]
     1595 |  .g_mbus_fmt = ov8830_g_mbus_fmt,
          |                ^~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>