(port-to-v4.5) t4ka3: Rename entities types to functions
MEDIA_ENT_T_V4L2_SUBDEV_SENSOR -> MEDIA_ENT_F_CAM_SENSOR

in accordance with commit 4ca72efaeffd ("[media] uapi/media.h: Rename
entities types to functions") added on v4.5-rc1.

Fixes build errors like the following:

        micam/atomisp-ov5693.c: In function ‘ov5693_probe’:
        micam/atomisp-ov5693.c:2235:35: error: ‘MEDIA_ENT_T_V4L2_SUBDEV_SENSOR’ undeclared (first use in this function); did you mean ‘MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN’?
         2235 |         dev->sd.entity.function = MEDIA_ENT_T_V4L2_SUBDEV_SENSOR;
              |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              |                                   MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>